# Generated by Django 2.1.5 on 2020-05-25 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200525_0722'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotel',
            new_name='Gallery',
        ),
    ]
